#Requires -Version 5.1
<#
.SYNOPSIS
  Copies Share My Thing to a local folder and builds wear + mobile APKs.

  Google Drive paths break KSP/Gradle incremental builds, so we mirror the
  project to a local directory, compile there, then copy APKs back to dist/.

.USAGE
  .\build-local.ps1              # debug APKs (default)
  .\build-local.ps1 -Release     # release APKs
  .\build-local.ps1 -SkipCopy    # rebuild using existing local copy only
  .\build-local.ps1 -InstallWear  # build wear debug APK and adb install to connected watch
  .\build-local.ps1 -InstallMobile # build mobile debug APK and adb install to connected phone

  Play Console: one listing, applicationId com.sharemyththing, upload both wear and mobile
  APKs/AABs signed with the same key.
#>
[CmdletBinding()]
param(
    [switch] $Release,
    [switch] $SkipCopy,
    [switch] $InstallWear,
    [switch] $InstallMobile,
    [string] $BuildDir = $(Join-Path $env:LOCALAPPDATA "ShareMyThing-build"),
    [string] $JavaHome = ""
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path

function Find-AndroidStudioJbr {
    $candidates = @(
        "$env:LOCALAPPDATA\Programs\Android Studio\jbr",
        "$env:ProgramFiles\Android\Android Studio\jbr",
        "$env:ProgramFiles\Android\Android Studio1\jbr"
    )
    foreach ($path in $candidates) {
        if (Test-Path (Join-Path $path "bin\java.exe")) {
            return $path
        }
    }
    return $null
}

function Write-Step([string] $Message) {
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Write-LocalProperties {
    param(
        [string] $TargetDir,
        [string] $SourceRoot
    )
    $sdkDir = $null
    $sourceProps = Join-Path $SourceRoot "local.properties"
    if (Test-Path $sourceProps) {
        $line = Get-Content $sourceProps | Where-Object { $_ -match '^sdk\.dir=' } | Select-Object -First 1
        if ($line) {
            $raw = ($line -replace '^sdk\.dir=', '').Trim()
            $sdkDir = $raw -replace '\\:', ':' -replace '\\\\', '\'
        }
    }
    if (-not $sdkDir -and $env:ANDROID_HOME) {
        $sdkDir = $env:ANDROID_HOME
    }
    if (-not $sdkDir) {
        $sdkDir = Join-Path $env:LOCALAPPDATA "Android\Sdk"
    }
    if (-not (Test-Path $sdkDir)) {
        throw "Android SDK not found at $sdkDir. Set sdk.dir in local.properties or install Android Studio."
    }

    $escaped = ($sdkDir -replace '\\', '/')
    @(
        "## Generated by build-local.ps1",
        "sdk.dir=$escaped"
    ) | Set-Content -Path (Join-Path $TargetDir "local.properties") -Encoding ASCII
    Write-Host "  SDK: $sdkDir"
}

function Find-BuiltApk {
    param(
        [string] $BuildDir,
        [string] $ModuleName,
        [string] $Variant
    )
    $expected = Join-Path $BuildDir "$ModuleName\build\outputs\apk\$Variant\$ModuleName-$Variant.apk"
    if (Test-Path $expected) {
        return $expected
    }
    $fallback = Get-ChildItem -Path (Join-Path $BuildDir "$ModuleName\build\outputs\apk\$Variant") -Filter "*.apk" -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1
    if ($fallback) {
        return $fallback.FullName
    }
    throw "Build succeeded but APK not found for $ModuleName ($Variant)"
}

$GradleTask = if ($Release) { "assembleRelease" } else { "assembleDebug" }
$Variant = if ($Release) { "release" } else { "debug" }
$DistDir = Join-Path $ProjectRoot "dist"
$WearDistName = if ($Release) { "ShareMyThing-wear-release-unsigned.apk" } else { "ShareMyThing-wear-debug.apk" }
$MobileDistName = if ($Release) { "ShareMyThing-mobile-release-unsigned.apk" } else { "ShareMyThing-mobile-debug.apk" }
$WearDistPath = Join-Path $DistDir $WearDistName
$MobileDistPath = Join-Path $DistDir $MobileDistName

if (-not $JavaHome) {
    $JavaHome = Find-AndroidStudioJbr
}

if (-not $JavaHome -or -not (Test-Path (Join-Path $JavaHome "bin\java.exe"))) {
    throw "Could not find Android Studio JBR. Install Android Studio or pass -JavaHome."
}

if (-not $SkipCopy) {
    Write-Step "Copying project to local build folder"
    Write-Host "  From: $ProjectRoot"
    Write-Host "  To:   $BuildDir"

    New-Item -ItemType Directory -Force -Path $BuildDir | Out-Null

    $robocopyArgs = @(
        $ProjectRoot,
        $BuildDir,
        "/MIR",
        "/XD", ".gradle", "build", "wear\build", "mobile\build", "core\build", ".idea", ".kotlin", "dist", ".git",
        "/XF", "local.properties",
        "/NFL", "/NDL", "/NJH", "/NJS", "/nc", "/ns", "/np"
    )
    & robocopy @robocopyArgs | Out-Null
    $robocopyExit = $LASTEXITCODE
    if ($robocopyExit -ge 8) {
        throw "robocopy failed with exit code $robocopyExit"
    }
} else {
    Write-Step "Skipping copy (-SkipCopy); using $BuildDir"
    if (-not (Test-Path (Join-Path $BuildDir "gradlew.bat"))) {
        throw "Local build folder is missing gradlew.bat. Run without -SkipCopy first."
    }
}

Write-Step "Configuring Android SDK"
Write-LocalProperties -TargetDir $BuildDir -SourceRoot $ProjectRoot

Write-Step "Building $GradleTask for :wear and :mobile"
Write-Host "  JAVA_HOME: $JavaHome"

$env:JAVA_HOME = $JavaHome
Push-Location $BuildDir
try {
    & .\gradlew.bat ":wear:$GradleTask" ":mobile:$GradleTask" --no-daemon
    if ($LASTEXITCODE -ne 0) {
        throw "Gradle build failed with exit code $LASTEXITCODE"
    }
} finally {
    Pop-Location
}

$BuiltWearApk = Find-BuiltApk -BuildDir $BuildDir -ModuleName "wear" -Variant $Variant
$BuiltMobileApk = Find-BuiltApk -BuildDir $BuildDir -ModuleName "mobile" -Variant $Variant

Write-Step "Copying APKs to dist/"
New-Item -ItemType Directory -Force -Path $DistDir | Out-Null
Copy-Item -Path $BuiltWearApk -Destination $WearDistPath -Force
Copy-Item -Path $BuiltMobileApk -Destination $MobileDistPath -Force

Write-Host ""
Write-Host "Build complete." -ForegroundColor Green
Write-Host "Wear APK:" -ForegroundColor Green
Write-Host "  $WearDistPath"
Write-Host "Mobile APK:" -ForegroundColor Green
Write-Host "  $MobileDistPath"

$adb = Join-Path $env:LOCALAPPDATA "Android\Sdk\platform-tools\adb.exe"
if ($InstallWear -or $InstallMobile) {
    if (-not (Test-Path $adb)) {
        throw "adb not found at $adb"
    }
}

if ($InstallWear) {
    Write-Step "Installing wear APK via adb"
    & $adb install -r $WearDistPath
    if ($LASTEXITCODE -ne 0) {
        throw "adb install failed with exit code $LASTEXITCODE"
    }
    Write-Host "Wear APK installed on connected device." -ForegroundColor Green
}

if ($InstallMobile) {
    Write-Step "Installing mobile APK via adb"
    & $adb install -r $MobileDistPath
    if ($LASTEXITCODE -ne 0) {
        throw "adb install failed with exit code $LASTEXITCODE"
    }
    Write-Host "Mobile APK installed on connected device." -ForegroundColor Green
}
