#Requires -Version 5.1
<#
.SYNOPSIS
  Copies Share My Thing to a local folder and builds the APK.

  Google Drive paths break KSP/Gradle incremental builds, so we mirror the
  project to a local directory, compile there, then copy the APK back to dist/.

.USAGE
  .\build-local.ps1              # debug APK (default)
  .\build-local.ps1 -Release     # release APK
  .\build-local.ps1 -SkipCopy    # rebuild using existing local copy only
  .\build-local.ps1 -Install     # build debug APK and adb install to connected watch
#>
[CmdletBinding()]
param(
    [switch] $Release,
    [switch] $SkipCopy,
    [switch] $Install,
    [string] $BuildDir = $(Join-Path $env:LOCALAPPDATA "ShareMyThing-build"),
    [string] $JavaHome = ""
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path

function Find-AndroidStudioJbr {
    $candidates = @(
        "$env:LOCALAPPDATA\Programs\Android Studio\jbr",
        "$env:ProgramFiles\Android\Android Studio\jbr",
        "$env:ProgramFiles\Android\Android Studio1\jbr"
    )
    foreach ($path in $candidates) {
        if (Test-Path (Join-Path $path "bin\java.exe")) {
            return $path
        }
    }
    return $null
}

function Write-Step([string] $Message) {
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Write-LocalProperties {
    param(
        [string] $TargetDir,
        [string] $SourceRoot
    )
    $sdkDir = $null
    $sourceProps = Join-Path $SourceRoot "local.properties"
    if (Test-Path $sourceProps) {
        $line = Get-Content $sourceProps | Where-Object { $_ -match '^sdk\.dir=' } | Select-Object -First 1
        if ($line) {
            $raw = ($line -replace '^sdk\.dir=', '').Trim()
            $sdkDir = $raw -replace '\\:', ':' -replace '\\\\', '\'
        }
    }
    if (-not $sdkDir -and $env:ANDROID_HOME) {
        $sdkDir = $env:ANDROID_HOME
    }
    if (-not $sdkDir) {
        $sdkDir = Join-Path $env:LOCALAPPDATA "Android\Sdk"
    }
    if (-not (Test-Path $sdkDir)) {
        throw "Android SDK not found at $sdkDir. Set sdk.dir in local.properties or install Android Studio."
    }

    $escaped = ($sdkDir -replace '\\', '/')
    @(
        "## Generated by build-local.ps1",
        "sdk.dir=$escaped"
    ) | Set-Content -Path (Join-Path $TargetDir "local.properties") -Encoding ASCII
    Write-Host "  SDK: $sdkDir"
}

$GradleTask = if ($Release) { "assembleRelease" } else { "assembleDebug" }
$ApkRelativePath = if ($Release) {
    "app\build\outputs\apk\release\app-release-unsigned.apk"
} else {
    "app\build\outputs\apk\debug\app-debug.apk"
}
$DistDir = Join-Path $ProjectRoot "dist"
$DistApkName = if ($Release) { "ShareMyThing-release-unsigned.apk" } else { "ShareMyThing-debug.apk" }
$DistApkPath = Join-Path $DistDir $DistApkName

if (-not $JavaHome) {
    $JavaHome = Find-AndroidStudioJbr
}

if (-not $JavaHome -or -not (Test-Path (Join-Path $JavaHome "bin\java.exe"))) {
    throw "Could not find Android Studio JBR. Install Android Studio or pass -JavaHome."
}

if (-not $SkipCopy) {
    Write-Step "Copying project to local build folder"
    Write-Host "  From: $ProjectRoot"
    Write-Host "  To:   $BuildDir"

    New-Item -ItemType Directory -Force -Path $BuildDir | Out-Null

    $robocopyArgs = @(
        $ProjectRoot,
        $BuildDir,
        "/MIR",
        "/XD", ".gradle", "build", "app\build", ".idea", ".kotlin", "dist", ".git",
        "/XF", "local.properties",
        "/NFL", "/NDL", "/NJH", "/NJS", "/nc", "/ns", "/np"
    )
    & robocopy @robocopyArgs | Out-Null
    $robocopyExit = $LASTEXITCODE
    if ($robocopyExit -ge 8) {
        throw "robocopy failed with exit code $robocopyExit"
    }
} else {
    Write-Step "Skipping copy (-SkipCopy); using $BuildDir"
    if (-not (Test-Path (Join-Path $BuildDir "gradlew.bat"))) {
        throw "Local build folder is missing gradlew.bat. Run without -SkipCopy first."
    }
}

Write-Step "Configuring Android SDK"
Write-LocalProperties -TargetDir $BuildDir -SourceRoot $ProjectRoot

Write-Step "Building $GradleTask"
Write-Host "  JAVA_HOME: $JavaHome"

$env:JAVA_HOME = $JavaHome
Push-Location $BuildDir
try {
    & .\gradlew.bat $GradleTask --no-daemon
    if ($LASTEXITCODE -ne 0) {
        throw "Gradle build failed with exit code $LASTEXITCODE"
    }
} finally {
    Pop-Location
}

$BuiltApk = Join-Path $BuildDir $ApkRelativePath
if (-not (Test-Path $BuiltApk)) {
    # Release builds may be signed differently; fall back to any matching APK.
    $variant = if ($Release) { "release" } else { "debug" }
    $fallback = Get-ChildItem -Path (Join-Path $BuildDir "app\build\outputs\apk\$variant") -Filter "*.apk" -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1
    if ($fallback) {
        $BuiltApk = $fallback.FullName
    } else {
        throw "Build succeeded but APK not found at $BuiltApk"
    }
}

Write-Step "Copying APK to dist/"
New-Item -ItemType Directory -Force -Path $DistDir | Out-Null
Copy-Item -Path $BuiltApk -Destination $DistApkPath -Force

Write-Host ""
Write-Host "Build complete." -ForegroundColor Green
Write-Host "APK (send this file):" -ForegroundColor Green
Write-Host "  $DistApkPath"

if ($Install) {
    Write-Step "Installing via adb"
    $adb = Join-Path $env:LOCALAPPDATA "Android\Sdk\platform-tools\adb.exe"
    if (-not (Test-Path $adb)) {
        throw "adb not found at $adb"
    }
    & $adb install -r $DistApkPath
    if ($LASTEXITCODE -ne 0) {
        throw "adb install failed with exit code $LASTEXITCODE"
    }
    Write-Host "Installed on connected device." -ForegroundColor Green
}
